var serve_dropdown=[
	{
		tot:[
			{
				title:'售后服务',
				data:[
					{'item':'物流与配送'},
					{'item':'上门安装'},
					{'item':'退换货服务'},
					{'item':'手机维修'},
					{'item':'延保服务'},
					{'item':'家电回收'}
				]
			},
			{
				title:'帮助服务',
				data:[
					{'item':'焦点问题'},
					{'item':'账户安全'},
					{'item':'签收与验货'},
					{'item':'分期付款'},
					{'item':'退款说明'},
					{'item':'优惠券说明'}
				]
			}
		]
	}
]
$('.serve-dropdown').prepend($('#serve-dropdown-data').render(serve_dropdown));

var mainshow_inside =[
	{
		tot:[
			{
				font:'&#xe6b2;',
				title:'服饰鞋帽',
				title_data:[
					'风衣',
					'夹克',
					'保暖内衣',
					'内裤',
					'商务鞋',
					'休闲鞋'
				],
				item0:[
					{
						item0_title:'品质男装',
						item0_data:[
							'夹克',
							'风衣',
							'休闲裤',
							'牛仔裤',
							'衬衫',
							'针织衫',
							'T恤',
							'POLO衫',
							'西装',
							'西裤',
							'西服套装'
						]
					},
					{
						item0_title:'时尚女装',
						item0_data:[
							'连衣裙',
							'半身裙',
							'T恤',
							'衬衫',
							'针织衫',
							'短外套',
							'打底裤',
							'休闲裤',
							'牛仔裤',
							'风衣',
							'西装',
							'婚纱/礼服/旗袍'
						]
					},
					{
						item0_title:'服饰配件',
						item0_data:[
							'太阳镜/眼镜',
							'围巾',
							'手套',
							'丝巾/披肩',
							'帽子',
							'男士皮带'
						]
					}
				],
				item1:[
					{
						item1_title:'潮流鞋靴',
						item1_data:[
							'商务鞋',
							'休闲鞋',
							'帆布鞋',
							'板鞋',
							'功能鞋',
							'女士单鞋',
							'男单鞋',
							'男士家居拖鞋',
							'女士家居拖鞋'
						]
					},
					{
						item1_title:'精品内衣',
						item1_data:[
							'男士内裤',
							'男袜',
							'女袜',
							'抹胸/背心',
							'女士内裤',
							'打底裤/丝袜',
							'睡袍/睡裙',
							'文胸',
							'情趣内衣',
							'睡袍/睡裙',
							'家居服'
						]
					}
				],
				item2:[
					{
						item2_title:'品牌',
						item2_data:[
							'其采',
							'创都',
							'BEBEERU',
							'南极人陌南',
							'卡尊',
							'金猴',
							'羊骑士',
							'红豆',
							'花花公子',
							'浪莎',
							'鼎赏',
							'赫嫀'
						]
					}
				],
				item3:[
					'img/cateadver-0-0.jpg',
					'img/cateadver-0-1.jpg'
				]
			},
			{
				font:'&#xe60f;',
				title:'运动户外',
				title_data:[
					'跑步鞋',
					'卫衣/套头衫',
					'登山鞋',
					'冲锋衣/裤',
					'望远镜'
				],
				item0:[
					{
						item0_title:'运动鞋服',
						item0_data:[
							'跑步鞋',
							'帆布鞋',
							'篮球鞋',
							'运动套装',
							'运动T恤',
							'休闲鞋/板鞋',
							'训练鞋',
							'羽毛球鞋',
							'足球鞋'
						]
					},
					{
						item0_title:'户外鞋服',
						item0_data:[
							'登山鞋',
							'户外休闲鞋',
							'徒步鞋',
							'越野鞋',
							'户外T恤',
							'户外棉服',
							'抓绒衣/裤',
							'户外配饰',
							'军警迷彩'
						]
					},
					{
						item0_title:'户外装备',
						item0_data:[
							'望远镜',
							'户外照明',
							'户外工具',
							'登山攀岩',
							'滑雪用品',
							'打火机/军刀',
							'军迷用品',
							'旅游用品',
							'垂钓用品'
						]
					}
				],
				item1:[
					{
						item1_title:'运动器械',
						item1_data:[
							'健身器械',
							'运动护具',
							'运动器材',
							'武术搏击'
						]
					},
					{
						item1_title:'体育娱乐',
						item1_data:[
							'羽毛球',
							'网球',
							'乒乓球',
							'篮球',
							'足球',
							'排球',
							'棋牌麻将'
						]
					},
					{
						item1_title:'骑行运动',
						item1_data:[
							'自行车整车',
							'骑行服鞋',
							'防护用品',
							'工具配件',
							'极限轮滑'
						]
					}
				],
				item2:[
					{
						item2_title:'品牌',
						item2_data:[
							'耐克',
							'阿迪达斯',
							'亚瑟士',
							'探路者',
							'凯乐石',
							'烤味佳',
							'佳钓尼',
							'诺可文',
							'狮凯路',
							'伊吉康',
							'李宁',
							'永久'
						]
					}
				],
				item3:[
					'img/cateadver-1-0.jpeg'
				]
			},
			{
				font:'&#xe631;',
				title:'钟表首饰',
				title_data:[
					'瑞士品牌表',
					'挂钟闹钟',
					'金银投资',
					'钻石饰品'
				],
				item0:[
					{
						item0_title:'精品腕表',
						item0_data:[
							'瑞士品牌表',
							'日韩品牌表',
							'国产品牌表',
							'时尚品牌表',
							'挂钟闹钟',
							'儿童手表'
						]
					},
					{
						item0_title:'珠宝首饰',
						item0_data:[
							'金银投资',
							'银饰品',
							'钻石饰品',
							'时尚饰品',
							'纯金K金饰品',
							'水晶玛瑙',
							'翡翠玉石',
							'宝石珍珠'
						]
					}
				],
				item1:[
					{
						item1_title:'鲜花礼品',
						item1_data:[
							'鲜花速递',
							'收藏品',
							'礼品文具',
							'礼卡礼券',
							'婚庆用品',
							'工艺礼品',
							'创意礼品',
							'瑞士军刀',
							'火机烟具'
						]
					}
				],
				item2:[
					{
						item2_title:'品牌',
						item2_data:[
							'天梭',
							'浪琴',
							'罗西尼',
							'卡西欧',
							'粤通',
							'多边金都',
							'周大福',
							'佐卡伊',
							'芝宝zippo',
							'卡们',
							'搜索天下',
							'派克'
						]
					}
				],
				item3:[
					'img/cateadver-2-0.jpg',
					'img/cateadver-2-1.jpg'
				]
			},
			{
				font:'&#xe66f;',
				title:'箱包奢品',
				title_data:[
					'商务包',
					'斜挎包',
					'钱包',
					'电脑包',
					'登机包',
					'奢品包'
				],
				item0:[
					{
						item0_title:'精品男包',
						item0_data:[
							'商务手提包',
							'斜挎包',
							'手包',
							'钱包/卡包',
							'皮带/礼盒'
						]
					},
					{
						item0_title:'时尚女包',
						item0_data:[
							'单肩包',
							'双肩包',
							'手拿包',
							'手提包',
							'斜挎包',
							'钱包/卡包',
							'时尚腰带'
						]
					},
					{
						item0_title:'奢侈品',
						item0_data:[
							'单肩包',
							'手提包',
							'钱包/卡包',
							'斜挎包'
						]
					}
				],
				item1:[
					{
						item1_title:'功能包',
						item1_data:[
							'电脑包',
							'休闲运动',
							'登山包',
							'学生包',
							'数码摄影',
							'工具包'
						]
					},
					{
						item1_title:'拉杆箱',
						item1_data:[
							'登机箱',
							'托运箱',
							'拉杆包',
							'旅行包',
							'旅行配件'
						]
					}
				],
				item2:[
					{
						item2_title:'品牌',
						item2_data:[
							'COACH',
							'MK',
							'OSDY',
							'赫卡斯',
							'七匹狼',
							'柏雅图',
							'诗薇儿',
							'瑞士军刀',
							'汉诺斯',
							'APPLE'
						]
					}
				],
				item3:[
					'img/cateadver-3-0.jpg'
				]
			}
		]
	}
]
$('.mainshow-inside').append($('#mainshow-inside-data').render(mainshow_inside));


var sitemap = [
	{
	    mapitem: [
	        {
	            droptitle: '主题促销',
	            droplist: [
	                {
	                    listitem: [
	                        '真划算',
	                        '抢购',
	                        '海外购',
	                        '国美定制'
	                    ]
	                },
	                {
	                    listitem: [
	                        '家电城',
	                        '服饰城',
	                        '国美超市',
	                        '家装馆'
	                    ]
	                },
	                {
	                    listitem: [
	                        '智能家居',
	                        '今日特卖',
	                        '新品抢先',
	                        '品牌街'
	                    ]
	                }
	            ]
	        },
	        {
	            droptitle: '特色分类',
	            droplist: [
	                {
	                    listitem: [
	                        '电视影音',
	                        '冰洗',
	                        '洗衣机',
	                        '空调',
	                        '厨卫生活'
	                    ]
	                },
	                {
	                    listitem: [
	                        '手机',
	                        '数码',
	                        '电脑办公',
	                        '精品配件',
	                        '汽车'
	                    ]
	                },
	                {
	                    listitem: [
	                        '住宅家具',
	                        '家装建材',
	                        '家居日用',
	                        '床品家纺',
	                        '黄金收藏'
	                    ]
	                },
	                {
	                    listitem: [
	                        '服饰鞋帽',
	                        '运动户外',
	                        '箱包奢品',
	                        '钟表首饰',
	                        '文化艺术'
	                    ]
	                },
	                {
	                    listitem: [
	                        '食品酒水',
	                        '医疗保健',
	                        '母婴玩具',
	                        '美妆个护'
	                    ]
	                }
	            ]
	        },
	        {
	            droptitle: '便捷服务',
	            droplist: [
	                {
	                    listitem: [
	                        '话费充值',
	                        '游戏点卡',
	                        '机票',
	                        '电影票',
	                        '美盈宝',
	                        '定期理财',
	                        '转让理财'
	                    ]
	                },
	                {
	                    listitem: [
	                        '流量充值',
	                        '酒店',
	                        '火车票',
	                        '演出票',
	                        '投金宝',
	                        '票据理财',
	                        '上门服务'
	                    ]
	                }
	            ]
	        },
	        {
	            droptitle: '更多热点',
	            droplist: [
	                {
	                    listitem: [
	                        '商家入驻',
	                        '企业采购',
	                        '国美社区',
	                        '购明白'
	                    ]
	                }
	            ]
	        },
	        {
	            droptitle: '国美旗下',
	            droplist: [
	                {
	                    listitem: [
	                        '多边金都',
	                        '国之美',
	                        '国美家装',
	                        '国美管家'
	                    ]
	                }
	            ]
	        }
	    ] 
	}
]


$('.sitemap-dropdown').append($('#tmp2').render(sitemap));
$('.sitemap-dropdown dl').first().addClass('none');
$('.sitemap-dropdown dl a:contains(国美定制)').after('<i class="new"></i>');
$('.sitemap-dropdown dl a:contains(企业采购)').after('<i class="hot"></i>');


var mainnav=[
	{
		data:[
			'服装鞋帽',
			'运动户外',
			'钟表首饰',
			'箱包奢品',
			'瑜伽专场'
		]
	}
]
$('.mainnav ul').append($('#mainnav_data').render(mainnav));




var keyword = [
	{
		data:[
			'iPhone 7',
			'返258元',
			'DW新品推荐',
			'抢红米4X',
			'平板518抢',
			'厨卫省500',
			'5折购',
			'洗衣机599'
		]
	}
]
$('.keyword').append($('#keyword-data').render(keyword));


var slide_box = [
	{
		pic:[
			'img/loop0.jpg',
			'img/loop1.jpg',
			'img/loop2.jpg',
			'img/loop3.jpg',
			'img/loop4.jpg',
			'img/loop5.jpg',
		]
	}
]
$('.slide_box').append($('#slide_box_data').render(slide_box));
$('.slide_box li').first().css('opacity','1');


var limit_box=[
	{
		tot:[
			{
				protitle:'蔻驰（COACH）女',
				bigprice:'699.00',
				smallprice:'¥999.00',
				pic:'img/limit-0.jpg',
			},
			{
				protitle:'银斯妮 925银耳钉',
				bigprice:'39.90',
				smallprice:'¥89.00',
				pic:'img/limit-1.jpg',
			}
		]
	}
]
$('.limit .box').prepend($('#limit_box_data').render(limit_box));
$('.limit .box').children().eq(0).addClass('first');
$('.limit .box').children().eq(1).addClass('second');



var contentbox=[
	{
		leftbox:[
			'img/leftbox0.jpeg',
			'img/leftbox1.jpg',
			'img/leftbox2.jpeg',
			'img/leftbox3.jpeg'
		],
		rightbox:[
			{
				pic:'img/rightbox0.jpeg',
				words:'满520减100'
			},
			{
				pic:'img/rightbox1.jpeg',
				words:'七匹狼'
			},
			{
				pic:'img/rightbox2.jpeg',
				words:'满99减10'
			},
			{
				pic:'img/rightbox3.jpg',
				words:'官方旗舰店'
			},
			{
				pic:'img/rightbox4.jpg',
				words:'220元起'
			},
			{
				pic:'img/rightbox5.jpg',
				words:'5折起'
			},
			{
				pic:'img/rightbox6.jpg',
				words:'卡尊'
			},
			{
				pic:'img/rightbox7.jpg',
				words:'喜德盛'
			}
		]
	}
]
$('.contentbox').prepend($('#contentbox-data').render(contentbox));
for(var i=0;i<4;i++){
	$('.contentbox .leftbox').children().eq(i).addClass('leftbox'+i);
}

var mrcd=[
	{
		choose:[
			'夏季潮流',
			'职场穿搭',
			'女神装扮',
			'商场同款'
		],
		tot:[
			{
				pic_a:'img/mrcd-0-0.jpeg',
				pic_b:'img/mrcd-0-1.jpeg',
				price_b:'49.00',
				intro_b:'男士皮肤衣',
				pic_c:'img/mrcd-0-2.jpeg',
				price_c:'228.00',
				intro_c:'吴亦凡同款',
				intro_d:'85折起',
				price_d:'1880.00',
				pic_d:'img/mrcd-0-3.jpeg',
				intro_e:'单肩包斜跨小包',
				price_e:'69.00',
				pic_e:'img/mrcd-0-4.jpeg',
				pic_f:'img/mrcd-0-5.jpeg'
			},
			{
				pic_a:'img/mrcd-1-0.jpeg',
				pic_b:'img/mrcd-1-1.jpeg',
				price_b:'49.00',
				intro_b:'商务休闲更有型',
				pic_c:'img/mrcd-1-2.jpeg',
				price_c:'78.00',
				intro_c:'复古绅士',
				intro_d:'超薄简约皮带',
				price_d:'719.00',
				pic_d:'img/mrcd-1-3.jpeg',
				intro_e:'下单减5元',
				price_e:'179.00',
				pic_e:'img/mrcd-1-4.jpeg',
				pic_f:'img/mrcd-1-5.jpeg'
			},
			{
				pic_a:'img/mrcd-2-0.jpeg',
				pic_b:'img/mrcd-2-1.jpeg',
				price_b:'109.00',
				intro_b:'满99减5',
				pic_c:'img/mrcd-2-2.jpeg',
				price_c:'79.00',
				intro_c:'冰冰同款抢先购',
				intro_d:'新店上新',
				price_d:'539.00',
				pic_d:'img/mrcd-2-3.jpeg',
				intro_e:'牛皮女包',
				price_e:'275.00',
				pic_e:'img/mrcd-2-4.jpeg',
				pic_f:'img/mrcd-2-5.jpeg'
			},
			{
				pic_a:'img/mrcd-3-0.jpeg',
				pic_b:'img/mrcd-3-1.jpeg',
				price_b:'499.00',
				intro_b:'经典飞行员系列',
				pic_c:'img/mrcd-3-2.jpeg',
				price_c:'49.00',
				intro_c:'户外登山双肩包',
				intro_d:'送备用皮表',
				price_d:'2488.00',
				pic_d:'img/mrcd-3-3.jpeg',
				intro_e:'万向轮拉杆箱',
				price_e:'559.00',
				pic_e:'img/mrcd-3-4.jpeg',
				pic_f:'img/mrcd-3-5.jpeg'
			}
		]
	}
]
$('.mrcd').append($('#mrcd-data').render(mrcd));



var jxhd=[
	{
		tot:[
			{
				bigpic:'img/jxhd-pic-0.jpeg',
				smallpic:'img/jxhd-logo-0.png',
				words:'T恤一元起'
			},
			{
				bigpic:'img/jxhd-pic-1.jpeg',
				smallpic:'img/jxhd-logo-1.png',
				words:'无门槛十元店铺券'
			},
			{
				bigpic:'img/jxhd-pic-2.jpeg',
				smallpic:'img/jxhd-logo-2.png',
				words:'全场160元起'
			},
			{
				bigpic:'img/jxhd-pic-3.jpeg',
				smallpic:'img/jxhd-logo-3.png',
				words:'拉杆箱199元起'
			}
		]
	}
]
$('.jxhd').append($('#jxhd-data').render(jxhd));

var floor_a=[
	{
		tot:[
			{
				fr:'1F',
				title:'品质男装',
				tips:[
					'牛仔裤',
					'休闲裤',
					'外套',
					'衬衫',
					'POLO衫',
					'T恤'
				],
				pic_a:'img/floor-1-0.jpg',
				logobox:[
					{
						pic:'img/floor-logo-1-0.jpg',
						words:'雅戈尔99元起'
					},
					{
						pic:'img/floor-logo-1-1.jpg',
						words:'39元起'
					},
					{
						pic:'img/floor-logo-1-2.jpg',
						words:'1元起'
					},
					{
						pic:'img/floor-logo-1-3.jpg',
						words:'19元起'
					},
					{
						pic:'img/floor-logo-1-4.jpg',
						words:'99元起'
					},
					{
						pic:'img/floor-logo-1-5.jpg',
						words:'波司登 领券更优'
					}
				],
				second:[
					{
						intro:'夏季新款圆领短袖T恤',
						price:'58.00',
						pic:'img/floor-1-1.jpg'
					},
					{
						intro:'南极人夏季薄款牛仔短裤',
						price:'69.00',
						pic:'img/floor-1-2.jpg'
					}
				],
				intro_c:'TRiES/才子男装',
				price_c:'149.00',
				logo_c:'img/floor-logo-1-6.jpeg',
				pic_c:'img/floor-1-3.jpg',
				pic_d:'img/floor-1-4.jpg',
				intro_e:'卡帝乐鳄鱼情侣内裤',
				price_e:'39.00',
				pic_e:'img/floor-1-5.jpg',
				third:[
					{
						intro:'纯色短袖男士POLO衫',
						price:'49.00',
						pic:'img/floor-1-6.jpg'
					},
					{
						intro:'休闲宽松五分裤',
						price:'49.00',
						pic:'img/floor-1-7.jpg'
					},
					{
						intro:'男士花花公子五分裤',
						price:'59.00',
						pic:'img/floor-1-8.jpg'
					}
				],
				fourth:[
					{
						pic:'img/floor-1-9.jpg',
						logopic:'img/floor-logo-1-7.jpg',
						intro:'皮肤衣48元抢购中'
					},
					{
						pic:'img/floor-1-10.jpg',
						logopic:'img/floor-logo-1-8.jpeg',
						intro:'夏装上新39元起'
					}
				]
			},
			{
				fr:'2F',
				title:'时尚女装',
				tips:[
					'连衣裙',
					'针织衫',
					'休闲裤',
					'打底衫',
					'衬衫',
					'T恤'
				],
				pic_a:'img/floor-2-0.jpg',
				logobox:[
					{
						pic:'img/floor-logo-2-0.jpg',
						words:'雅丽达海量新品'
					},
					{
						pic:'img/floor-logo-2-1.jpg',
						words:'莉妮吉尔2折起'
					},
					{
						pic:'img/floor-logo-2-2.jpg',
						words:'专注时尚韩范'
					},
					{
						pic:'img/floor-logo-2-3.jpg',
						words:'酷总会2.7折起'
					},
					{
						pic:'img/floor-logo-2-4.jpg',
						words:'满219减30'
					},
					{
						pic:'img/floor-logo-2-5.jpg',
						words:'浪莎9.9元起'
					}
				],
				second:[
					{
						intro:'破洞显瘦短裤',
						price:'42.00',
						pic:'img/floor-2-1.jpg'
					},
					{
						intro:'碎花雪纺连衣裙',
						price:'68.00',
						pic:'img/floor-2-2.jpg'
					}
				],
				intro_c:'碎花夏季印花连衣裙',
				price_c:'89.00',
				pic_c:'img/floor-2-3.jpg',
				logo_c:'img/floor-logo-2-6.jpg',
				pic_d:'img/floor-2-4.jpg',
				intro_e:'曼姿 超薄T裆连裤',
				price_e:'9.90',
				pic_e:'img/floor-2-5.jpg',
				third:[
					{
						intro:'沙滩碎花雪纺连衣裙',
						price:'79.00',
						pic:'img/floor-2-6.jpg'
					},
					{
						intro:'文艺复古棉麻连衣裙',
						price:'68.00',
						pic:'img/floor-2-7.jpg'
					},
					{
						intro:'冰丝绸性感睡裙',
						price:'59.00',
						pic:'img/floor-2-8.jpg'
					}
				],
				fourth:[
					{
						pic:'img/floor-2-9.jpg',
						logopic:'img/floor-logo-2-7.jpg',
						intro:'皮肤衣48元抢购中'
					},
					{
						pic:'img/floor-2-10.jpg',
						logopic:'img/floor-logo-2-8.jpeg',
						intro:'夏装上新39元起'
					}
				]
			}
		]
	}
]
$('.floor-all').append($('#floor-data-a').render(floor_a));

var floor_b=[
	{
		tot:[
			{
				fr:'3F',
				title:'时尚手表',
				tips:[
					'浪琴',
					'松拓',
					'卡西欧',
					'DW手表'
				],
				pic_a:'img/floor-3-0.jpg',
				logobox:[
					{
						pic:'img/floor-logo-3-0.jpg',
						words:'CK'
					},
					{
						pic:'img/floor-logo-3-1.png',
						words:'依波'
					},
					{
						pic:'img/floor-logo-3-2.png',
						words:'宾格'
					},
					{
						pic:'img/floor-logo-3-3.jpg',
						words:'精工'
					},
					{
						pic:'img/floor-logo-3-4.jpg',
						words:'天王'
					},
					{
						pic:'img/floor-logo-3-5.jpg',
						words:'美度'
					}
				],
				second:[
					{
						intro:'美度贝伦赛丽系列',
						price:'4440.00',
						pic:'img/floor-3-1.jpeg'
					},
					{
						intro:'宾格镂空机械表',
						price:'378.00',
						pic:'img/floor-3-2.jpeg'
					},
					{
						intro:'下单立减100元',
						price:'799.00',
						pic:'img/floor-3-4.jpeg'
					}
				],
				intro_c:'飞亚达四叶草女士腕表',
				price_c:'<i class="grey">满100立减5</i>',
				pic_c:'img/floor-3-3.jpg',
				logo_c:'img/floor-logo-3-6.jpg',
				intro_d:'格雅休闲石英手表',
				price_d:'199.00',
				pic_d:'img/floor-3-5.jpeg',
				third:[
					{
						logopic:'img/floor-3-6.jpeg',
						intro:'雷泽时尚手表',
						price:'3.5折起',
						bigpic:'img/floor-3-7.jpeg'
					},
					{
						logopic:'img/floor-3-8.jpeg',
						intro:'浪琴腕表',
						price:'7折起',
						bigpic:'img/floor-3-9.jpeg'
					}
				],
				fourth:[
					{
						pic:'img/floor-3-10.png',
						logopic:'img/floor-logo-3-7.jpeg',
						intro:'5折起'
					}
				]
			},
			{
				fr:'4F',
				title:'箱包奢品',
				tips:[
					'学生包',
					'时尚女包',
					'拉杆箱',
					'商务手提包',
					'皮带/礼盒',
					'电脑包',
					'男士手包'
				],
				pic_a:'img/floor-4-0.jpeg',
				logobox:[
					{
						pic:'img/floor-logo-4-0.jpg',
						words:'七匹狼'
					},
					{
						pic:'img/floor-logo-4-1.jpeg',
						words:'莫尔克'
					},
					{
						pic:'img/floor-logo-4-2.jpg',
						words:'诗薇儿'
					},
					{
						pic:'img/floor-logo-4-3.jpg',
						words:'OSDY'
					},
					{
						pic:'img/floor-logo-4-4.jpg',
						words:'swissgear'
					},
					{
						pic:'img/floor-logo-4-5.jpeg',
						words:'蔻驰'
					}
				],
				second:[
					{
						intro:'斐格男士单肩包',
						price:'148.00',
						pic:'img/floor-4-1.jpg'
					},
					{
						intro:'伦威保罗男士胸包',
						price:'118.00',
						pic:'img/floor-4-2.jpg'
					},
					{
						intro:'20寸万向轮拉杆箱',
						price:'299.00',
						pic:'img/floor-4-4.jpeg'
					}
				],
				intro_c:'COACH',
				price_c:'<i class="minPrice">899.00</i>',
				pic_c:'img/floor-4-3.jpeg',
				logo_c:'img/floor-logo-4-6.jpeg',
				intro_d:'侍卫军刀双肩电脑包',
				price_d:'136.00',
				pic_d:'img/floor-4-5.jpeg',
				third:[
					{
						logopic:'img/floor-4-6.jpeg',
						intro:'汉诺斯休闲双肩包',
						price:'<i class="minPrice">119.00</i>',
						bigpic:'img/floor-4-7.jpeg'
					},
					{
						logopic:'img/floor-4-8.jpg',
						intro:'丹爵手提包',
						price:'<i class="minPrice">399.00</i>',
						bigpic:'img/floor-4-9.jpg'
					}
				],
				fourth:[
					{
						pic:'img/floor-4-10.jpg',
						logopic:'img/floor-logo-4-7.jpg',
						intro:'五折起'
					}
				]
			}
		]
	}
]
$('.floor-all').append($('#floor-data-b').render(floor_b));




var floor_a_a=[
	{
		tot:[
			{
				fr:'5F',
				title:'潮流鞋靴',
				tips:[
					'手套',
					'太阳镜/眼睛',
					'板鞋',
					'帆布鞋',
					'休闲鞋',
					'商务鞋'
				],
				pic_a:'img/floor-5-0.jpeg',
				logobox:[
					{
						pic:'img/floor-logo-5-0.jpg',
						words:'1折起'
					},
					{
						pic:'img/floor-logo-5-1.jpg',
						words:'3折起'
					},
					{
						pic:'img/floor-logo-5-2.jpg',
						words:'5折起'
					},
					{
						pic:'img/floor-logo-5-3.jpeg',
						words:'新店开业'
					},
					{
						pic:'img/floor-logo-5-4.jpg',
						words:'8折起'
					},
					{
						pic:'img/floor-logo-5-5.jpg',
						words:'9折'
					}
				],
				second:[
					{
						intro:'大盛公羊休闲皮鞋',
						price:'99.00',
						pic:'img/floor-5-1.jpeg'
					},
					{
						intro:'MR.KANG春秋单',
						price:'59.00',
						pic:'img/floor-5-2.jpeg'
					}
				],
				intro_c:'圣象休闲鞋',
				price_c:'399.00',
				logo_c:'img/floor-logo-5-6.jpeg',
				pic_c:'img/floor-5-3.jpeg',
				pic_d:'img/floor-5-4.jpeg',
				intro_e:'驿站公牛英伦休闲',
				price_e:'139.00',
				pic_e:'img/floor-5-5.jpeg',
				third:[
					{
						intro:'下单送袜子鞋垫',
						price:'139.00',
						pic:'img/floor-5-6.jpeg'
					},
					{
						intro:'婓朗纳休闲皮鞋',
						price:'138.00',
						pic:'img/floor-5-7.jpeg'
					},
					{
						intro:'春季百搭新品',
						price:'99.00',
						pic:'img/floor-5-8.jpeg'
					}
				],
				fourth:[
					{
						pic:'img/floor-5-9.jpeg',
						logopic:'img/floor-logo-5-7.jpeg',
						intro:'满88减10'
					},
					{
						pic:'img/floor-5-10.jpeg',
						logopic:'img/floor-logo-5-8.jpeg',
						intro:'满55减5元'
					}
				]
			},
			{
				fr:'6F',
				title:'运动户外',
				tips:[
					'跑步鞋',
					'卫衣/套头衫',
					'登山鞋',
					'户外休闲鞋',
					'冲锋衣/裤'
				],
				pic_a:'img/floor-6-0.jpeg',
				logobox:[
					{
						pic:'img/floor-logo-6-0.jpg',
						words:'耐克4折起'
					},
					{
						pic:'img/floor-logo-6-1.jpg',
						words:'阿迪达斯5折起'
					},
					{
						pic:'img/floor-logo-6-2.jpeg',
						words:'新百伦4折起'
					},
					{
						pic:'img/floor-logo-6-3.jpg',
						words:'探路者5折起'
					},
					{
						pic:'img/floor-logo-6-4.jpg',
						words:'佳钓尼5折起'
					},
					{
						pic:'img/floor-logo-6-5.jpg',
						words:'骆驼5折起'
					}
				],
				second:[
					{
						intro:'三叶草NEO女子运动',
						price:'119.00',
						pic:'img/floor-6-1.jpeg'
					},
					{
						intro:'耐克跑步鞋',
						price:'429.00',
						pic:'img/floor-6-2.jpeg'
					}
				],
				intro_c:'阿迪达斯T恤',
				price_c:'158.00',
				logo_c:'img/floor-logo-6-6.jpeg',
				pic_c:'img/floor-6-3.jpeg',
				pic_d:'img/floor-6-4.jpg',
				intro_e:'陈奕迅同款',
				price_e:'198.00',
				pic_e:'img/floor-6-5.jpeg',
				third:[
					{
						intro:'诺可文 户外帐篷休闲',
						price:'299.00',
						pic:'img/floor-6-6.jpeg'
					},
					{
						intro:'原始人烧烤工具全套',
						price:'168.00',
						pic:'img/floor-6-7.jpeg'
					},
					{
						intro:'阿迪达斯网面运动鞋',
						price:'458.00',
						pic:'img/floor-6-8.jpeg'
					}
				],
				fourth:[
					{
						pic:'img/floor-6-9.jpeg',
						logopic:'img/floor-logo-6-7.jpeg',
						intro:'阿迪达斯'
					},
					{
						pic:'img/floor-6-10.jpeg',
						logopic:'img/floor-logo-6-8.jpeg',
						intro:'骆驼'
					}
				]
			},
			{
				fr:'7F',
				title:'运动器械',
				tips:[
					'羽毛球',
					'篮球',
					'自行车',
					'极限轮滑',
					'器材/跑步机'
				],
				pic_a:'img/floor-7-0.jpeg',
				logobox:[
					{
						pic:'img/floor-logo-7-0.jpeg',
						words:'优步8折起'
					},
					{
						pic:'img/floor-logo-7-1.jpg',
						words:'舒华8折起'
					},
					{
						pic:'img/floor-logo-7-2.jpg',
						words:'雅马哈8折起'
					},
					{
						pic:'img/floor-logo-7-3.jpg',
						words:'多德士8折起'
					},
					{
						pic:'img/floor-logo-7-4.jpg',
						words:'毕梵低至3折'
					},
					{
						pic:'img/floor-logo-7-5.jpg',
						words:'永久低至5折'
					}
				],
				second:[
					{
						intro:'亿健跑步机',
						price:'2899.00',
						pic:'img/floor-7-1.jpeg'
					},
					{
						intro:'伊吉康跑步机',
						price:'1788.00',
						pic:'img/floor-7-2.jpeg'
					}
				],
				intro_c:'多德士美腰机8折',
				price_c:'118.00',
				logo_c:'img/floor-logo-7-6.jpg',
				pic_c:'img/floor-7-3.jpg',
				pic_d:'img/floor-7-4.jpeg',
				intro_e:'永久旗舰店',
				price_e:'1198.00',
				pic_e:'img/floor-7-5.jpeg',
				third:[
					{
						intro:'LINING李宁羽毛球',
						price:'199.00',
						pic:'img/floor-7-6.jpeg'
					},
					{
						intro:'斯伯丁篮球',
						price:'239.00',
						pic:'img/floor-7-7.jpeg'
					},
					{
						intro:'小乔XQIAO酷动跑',
						price:'458.00',
						pic:'img/floor-7-8.jpeg'
					}
				],
				fourth:[
					{
						pic:'img/floor-7-9.jpeg',
						logopic:'img/floor-logo-7-7.jpeg',
						intro:'运动器材8.5折'
					},
					{
						pic:'img/floor-7-10.jpeg',
						logopic:'img/floor-logo-7-8.jpeg',
						intro:'低至59元'
					}
				]
			}
		]
	}
]
$('.floor-all').append($('#floor-data-a').render(floor_a_a));



var floor_b_b=[
	{
		tot:[
			{
				fr:'8F',
				title:'首饰礼品',
				tips:[
					'周大福',
					'粤通',
					'ZIPPO',
					'派克'
				],
				pic_a:'img/floor-8-0.jpeg',
				logobox:[
					{
						pic:'img/floor-logo-8-0.jpg',
						words:'粤通国际'
					},
					{
						pic:'img/floor-logo-8-1.png',
						words:'旭平'
					},
					{
						pic:'img/floor-logo-8-2.jpeg',
						words:'银斯妮'
					},
					{
						pic:'img/floor-logo-8-3.jpg',
						words:'zippo'
					},
					{
						pic:'img/floor-logo-8-4.jpg',
						words:'搜藏天下'
					},
					{
						pic:'img/floor-logo-8-5.jpeg',
						words:'花港码头'
					}
				],
				second:[
					{
						intro:'四叶草项链女925银',
						price:'129.00',
						pic:'img/floor-8-1.jpeg'
					},
					{
						intro:'足金十二生肖转运珠',
						price:'489.00',
						pic:'img/floor-8-2.jpeg'
					},
					{
						intro:'派克（PARKER）',
						price:'138.00',
						pic:'img/floor-8-4.jpeg'
					}
				],
				intro_c:'梦克拉',
				price_c:'',
				pic_c:'img/floor-8-3.jpeg',
				logo_c:'img/floor-logo-8-6.jpeg',
				intro_d:'创意木刻画',
				price_d:'38.90',
				pic_d:'img/floor-8-5.jpeg',
				third:[
					{
						logopic:'img/floor-8-6.jpg',
						intro:'海普伊珊 925银项脸',
						price:'2折起',
						bigpic:'img/floor-8-7.jpeg'
					},
					{
						logopic:'img/floor-8-8.jpeg',
						intro:'zippo火机',
						price:'5折起',
						bigpic:'img/floor-8-9.jpeg'
					}
				],
				fourth:[
					{
						pic:'img/floor-8-10.jpeg',
						logopic:'img/floor-logo-8-7.jpeg',
						intro:'搜藏天下'
					}
				]
			}
		]
	}
]
$('.floor-all').append($('#floor-data-b').render(floor_b_b));






var hot_main_box=[
	{
		tot:[
			'女装内衣',
			'男装内衣',
			'精品鞋靴',
			'运动户外',
			'箱包奢品',
			'精选腕表',
			'礼品首饰',
			'健身器械'
		]
	}
]
$('.hot-box .hot-main .box ul').append($('#hot_main_box').render(hot_main_box));

var box_content=[
	{
		tot:[
			{
				hotlist:[
					{
						pic:'img/hotlist-0-0.jpg',
						words:'伊秋梦紫 2017夏季新款韩版',
						price:'68.00'
					},
					{
						pic:'img/hotlist-0-1.jpg',
						words:'窈兹 夏季新款女装韩版V领喇',
						price:'79.00'
					},
					{
						pic:'img/hotlist-0-2.jpg',
						words:'Mistletoe2017新款半袖衣服',
						price:'39.90'
					},
					{
						pic:'img/hotlist-0-3.jpg',
						words:'韩都衣舍2017韩版女装夏装新',
						price:'146.00'
					},
					{
						pic:'img/hotlist-0-4.jpg',
						words:'葩葩乐奇V领中长款修身连衣',
						price:'39.90'
					},
					{
						pic:'img/hotlist-0-5.jpg',
						words:'2017女式花边牛仔短裤破洞显',
						price:'49.00'
					},
					{
						pic:'img/hotlist-0-6.jpg',
						words:'佰伦世家夏天新款可爱宽松背',
						price:'58.00'
					},
					{
						pic:'img/hotlist-0-7.jpg',
						words:'古瑕 女睡衣2017春夏 女士仿',
						price:'59.00'
					},
					{
						pic:'img/hotlist-0-8.jpg',
						words:'曼姿MANZI 10D超薄T裆连裤',
						price:'9.90'
					},
					{
						pic:'img/hotlist-0-9.jpg',
						words:'内慧 夏白色冰丝无痕带胸垫文',
						price:'32.00'
					},
					{
						pic:'img/hotlist-0-10.jpg',
						words:'【浪莎】丝袜5双 超薄连裤袜',
						price:'29.00'
					},
					{
						pic:'img/hotlist-0-11.jpg',
						words:'祺美佳人纯色无痕无钢圈横纹',
						price:'59.00'
					}
				]
			},
			{
				hotlist:[
					{
						pic:'img/hotlist-1-0.jpg',
						words:'夏季T恤男短袖翻领纯棉大码',
						price:'59.00'
					},
					{
						pic:'img/hotlist-1-1.jpg',
						words:'卡郎琪 男士新款夏装短袖',
						price:'69.00'
					},
					{
						pic:'img/hotlist-1-2.jpg',
						words:'男式牛仔裤短款 牛仔短裤休闲',
						price:'49.00'
					},
					{
						pic:'img/hotlist-1-3.jpg',
						words:'FGN/富贵鸟 男装圆领短袖T恤',
						price:'1.00'
					},
					{
						pic:'img/hotlist-1-4.jpg',
						words:'时尚简约商务休闲修身翻领纯',
						price:'49.00'
					},
					{
						pic:'img/hotlist-1-5.jpg',
						words:'G&G男装新品夏季薄款棉男士',
						price:'358.00'
					},
					{
						pic:'img/hotlist-1-6.jpg',
						words:'【修身打底 棉质排汗】3件装 ',
						price:'38.80'
					},
					{
						pic:'img/hotlist-1-7.jpg',
						words:'花花公子男士五分裤 家居服休',
						price:'59.00'
					},
					{
						pic:'img/hotlist-1-8.jpg',
						words:'宛如美英国卫裤罐装第十代26',
						price:'24.90'
					},
					{
						pic:'img/hotlist-1-9.jpg',
						words:'3双浪莎夏季薄款男士丝袜 吸',
						price:'12.80'
					},
					{
						pic:'img/hotlist-1-10.jpg',
						words:'卡帝乐鳄鱼男袜棉质商务休闲',
						price:'19.90'
					},
					{
						pic:'img/hotlist-1-11.jpg',
						words:'花花公子男士三分裤休闲沙滩',
						price:'32.00'
					}
				]
			},
			{
				hotlist:[
					{
						pic:'img/hotlist-2-0.jpg',
						words:'2017夏季新品沙滩鞋 时尚休闲超纤露趾透气凉鞋男(棕色 43)',
						price:'79.00'
					},
					{
						pic:'img/hotlist-2-1.jpg',
						words:'花花公子休闲鞋男鞋秋冬板鞋',
						price:'198.00'
					},
					{
						pic:'img/hotlist-2-2.jpg',
						words:'斐朗纳2016新款时尚男鞋男式',
						price:'29.00'
					},
					{
						pic:'img/hotlist-2-3.jpg',
						words:'PLOVER新款男士皮鞋男商务',
						price:'199.00'
					},
					{
						pic:'img/hotlist-2-4.jpg',
						words:'Jinho金猴 金猴专业户外作训',
						price:'188.00'
					},
					{
						pic:'img/hotlist-2-5.jpg',
						words:'男士人字拖男拖鞋夏季潮拖男',
						price:'59.00'
					},
					{
						pic:'img/hotlist-2-6.jpg',
						words:'羽陌伦诗夏季粗跟中跟跟女鞋',
						price:'79.00'
					},
					{
						pic:'img/hotlist-2-7.jpg',
						words:'Daphne/达芙妮春季新款女鞋',
						price:'69.00'
					},
					{
						pic:'img/hotlist-2-8.jpg',
						words:'羽陌伦诗夏季新款露趾鱼嘴一',
						price:'129.00'
					},
					{
						pic:'img/hotlist-2-9.jpg',
						words:'花花公子女鞋 2015新款精美',
						price:'198.00'
					},
					{
						pic:'img/hotlist-2-10.jpg',
						words:'Daphne/达芙妮春季女鞋低跟',
						price:'69.00'
					},
					{
						pic:'img/hotlist-2-11.jpg',
						words:'古奇天伦高跟鞋女2017春新款',
						price:'158.00'
					}
				]
			},
			{
				hotlist:[
					{
						pic:'img/hotlist-3-0.jpg',
						words:'adidas阿迪达斯NEO 男新款',
						price:'238.00'
					},
					{
						pic:'img/hotlist-3-1.jpg',
						words:'阿迪达斯2017春秋女款拼接撞',
						price:'268.00'
					},
					{
						pic:'img/hotlist-3-2.jpg',
						words:'阿迪达斯三叶草2017新款女子',
						price:'278.00'
					},
					{
						pic:'img/hotlist-3-3.jpg',
						words:'Nike 耐克 NIKE MAX 2017 女',
						price:'558.00'
					},
					{
						pic:'img/hotlist-3-4.jpg',
						words:'2017Nike 耐克官方 NIKE ',
						price:'338.00'
					},
					{
						pic:'img/hotlist-3-5.jpg',
						words:'2017新款耐克男鞋AIR MAX黑',
						price:'398.00'
					},
					{
						pic:'img/hotlist-3-6.jpg',
						words:'飞佳佳皮肤衣男女款春夏季户',
						price:'79.00'
					},
					{
						pic:'img/hotlist-3-7.jpg',
						words:'美骆世家CAMSSOO徒步鞋男',
						price:'99.00'
					},
					{
						pic:'img/hotlist-3-8.jpg',
						words:'camel骆驼户外男款徒步鞋 防',
						price:'286.00'
					},
					{
						pic:'img/hotlist-3-9.jpg',
						words:'威迪瑞 云峰户外双人3-4人野',
						price:'199.00'
					},
					{
						pic:'img/hotlist-3-10.jpg',
						words:'考味佳 * 大号不锈钢烧烤架 家',
						price:'338.00'
					},
					{
						pic:'img/hotlist-3-11.jpg',
						words:'户外背包登山包双肩包男女大',
						price:'49.00'
					}
				]
			},
			{
				hotlist:[
					{
						pic:'img/hotlist-4-0.jpg',
						words:'Svale诗薇儿 男士牛皮自动扣',
						price:'59.90'
					},
					{
						pic:'img/hotlist-4-1.jpg',
						words:'抢！送钱包 伦威保罗男士胸包',
						price:'79.90'
					},
					{
						pic:'img/hotlist-4-2.jpg',
						words:'伦威保罗男士包商务休闲包男',
						price:'128.00'
					},
					{
						pic:'img/hotlist-4-3.jpg',
						words:'丹爵 头层牛皮 单肩包 斜挎包 ',
						price:'189.00'
					},
					{
						pic:'img/hotlist-4-4.jpg',
						words:'森泰英格2016新款男女出游登',
						price:'159.00'
					},
					{
						pic:'img/hotlist-4-5.jpg',
						words:'瑞吉仕 电脑双肩包男',
						price:'99.00'
					},
					{
						pic:'img/hotlist-4-6.jpg',
						words:'coach 蔻驰 男式经典LOGO长',
						price:'699.00'
					},
					{
						pic:'img/hotlist-4-7.jpg',
						words:'蔻驰COACH钱包新款女士拉',
						price:'418.00'
					},
					{
						pic:'img/hotlist-4-8.jpg',
						words:'MK 迈克.科尔斯 Michael Kors',
						price:'1059.00'
					},
					{
						pic:'img/hotlist-4-9.jpg',
						words:'COACH/蔲驰 71764 时尚经典',
						price:'638.00'
					},
					{
						pic:'img/hotlist-4-10.jpg',
						words:'OSDY拉杆箱万向轮旅行箱托',
						price:'598.00'
					},
					{
						pic:'img/hotlist-4-11.jpg',
						words:'苏克斯时尚男女行李箱旅行箱',
						price:'139.00'
					}
				]
			},
			{
				hotlist:[
					{
						pic:'img/hotlist-5-0.jpg',
						words:'新品Danie lWellington丹尼尔',
						price:'1290.00'
					},
					{
						pic:'img/hotlist-5-1.jpg',
						words:'天梭男表 力洛克系列全自动机',
						price:'2099.00'
					},
					{
						pic:'img/hotlist-5-2.jpg',
						words:'阿玛尼手表商务休闲时尚潮流',
						price:'669.00'
					},
					{
						pic:'img/hotlist-5-3.jpg',
						words:'【官方直营】罗西尼',
						price:'2169.00'
					},
					{
						pic:'img/hotlist-5-4.jpg',
						words:'ARMANI/阿玛尼男表商务腕表',
						price:'899.00'
					},
					{
						pic:'img/hotlist-5-5.jpg',
						words:'天梭TISSOT手表力洛克系列',
						price:'2488.00'
					},
					{
						pic:'img/hotlist-5-6.jpg',
						words:'Armani/阿玛尼独立秒盘黑色',
						price:'799.00'
					},
					{
						pic:'img/hotlist-5-7.jpg',
						words:'天梭/Tissot手表 力洛克系列 ',
						price:'2599.00'
					},
					{
						pic:'img/hotlist-5-8.jpg',
						words:'浪琴Longines-律雅系列机械',
						price:'6999.00'
					},
					{
						pic:'img/hotlist-5-9.jpg',
						words:'Seagull海鸥手表 海鸥情侣表',
						price:'1080.00'
					},
					{
						pic:'img/hotlist-5-10.jpg',
						words:'美度（MIDO）贝伦赛丽系列',
						price:'4598.00'
					},
					{
						pic:'img/hotlist-5-11.jpg',
						words:'欧米茄（Omega）碟飞系列',
						price:'17500.00'
					}
				]
			},
			{
				hotlist:[
					{
						pic:'img/hotlist-6-0.jpg',
						words:'xupingjewelry饰品 镀金欧美',
						price:'26.80'
					},
					{
						pic:'img/hotlist-6-1.jpg',
						words:'传世美钰 镀黄金金箔玫瑰花 ',
						price:'49.00'
					},
					{
						pic:'img/hotlist-6-2.jpg',
						words:'天鑫洋 Ag999足银贵字银元宝 ',
						price:'459.00'
					},
					{
						pic:'img/hotlist-6-3.jpg',
						words:'【超人系列五折限时抢】周大',
						price:'1480.00'
					},
					{
						pic:'img/hotlist-6-4.jpg',
						words:'芭法娜 天然紫水晶手链 女',
						price:'218.00'
					},
					{
						pic:'img/hotlist-6-5.jpg',
						words:'天鑫洋 AU750 18K金项链 水',
						price:'199.00'
					},
					{
						pic:'img/hotlist-6-6.jpg',
						words:'中国航天纪念钞(单张裸钞)',
						price:'110.00'
					},
					{
						pic:'img/hotlist-6-7.jpg',
						words:'雅高e卡北京上海通用 家乐福',
						price:'100.00'
					},
					{
						pic:'img/hotlist-6-8.jpg',
						words:'2016款易星电子烟套装戒烟产',
						price:'129.00'
					},
					{
						pic:'img/hotlist-6-9.jpg',
						words:'里约2016年奥运会纪念5枚银套',
						price:'378.00'
					},
					{
						pic:'img/hotlist-6-10.jpg',
						words:'之宝Zippo打火机 205经典镀',
						price:'145.00'
					},
					{
						pic:'img/hotlist-6-11.jpg',
						words:'创意圣诞节情人节礼品新奇特',
						price:'98.00'
					}
				]
			},
			{
				hotlist:[
					{
						pic:'img/hotlist-7-0.jpg',
						words:'永久折叠自行车7级变速20寸',
						price:'588.00'
					},
					{
						pic:'img/hotlist-7-1.jpg',
						words:'美国菲特尼斯跑步机家用多功',
						price:'1598.00'
					},
					{
						pic:'img/hotlist-7-2.jpg',
						words:'毕梵Bevan脚底按摩器足疗机 ',
						price:'299.00'
					},
					{
						pic:'img/hotlist-7-3.jpg',
						words:'阿米尼自行车22寸淑女自行车',
						price:'698.00'
					},
					{
						pic:'img/hotlist-7-4.jpg',
						words:'升浩SEHAT21C电动跑步机家',
						price:'1358.00'
					},
					{
						pic:'img/hotlist-7-5.jpg',
						words:'优步600跑步机家用款多功能',
						price:'1929.00'
					},
					{
						pic:'img/hotlist-7-6.jpg',
						words:'伊吉康M460 跑步机 多功能家',
						price:'2649.00'
					},
					{
						pic:'img/hotlist-7-7.jpg',
						words:'舒华国美专营跑步机家用静音',
						price:'3880.00'
					},
					{
						pic:'img/hotlist-7-8.jpg',
						words:'爱玛莎瑜伽 健身美体瑜伽拉力',
						price:'19.90'
					},
					{
						pic:'img/hotlist-7-9.jpg',
						words:'多德士（DDS）健腹轮/俯卧',
						price:'48.00'
					},
					{
						pic:'img/hotlist-7-10.jpg',
						words:'S型俯卧撑支架 胸肌家用健身',
						price:'49.90'
					},
					{
						pic:'img/hotlist-7-11.jpg',
						words:'李宁LINING轻质初学休闲进阶全碳素羽毛球拍 A880(红色)',
						price:'139.00'
					}
				]
			}
		]	
	}
]
$('.hot-box .hot-main .box').append($('#box_content').render(box_content));

var bottom_list=[
	{
		tot:[
			{
				title:'女士精选',
				icon:'&#xe601;',
				list:[
					'连衣裙',
					'T恤',
					'衬衫',
					'抹胸/背心',
					'女士内裤',
					'打底裤/丝',
					'睡袍/睡裙',
					'凉鞋',
					'高跟鞋',
					'平底鞋',
					'帆布鞋',
					'休闲鞋'
				]
			},
			{
				title:'男士精选',
				icon:'&#xe600;',
				list:[
					'T恤',
					'Polo衫',
					'衬衫',
					'短裤',
					'休闲裤',
					'男士内裤',
					'男袜',
					'牛仔裤',
					'男靴',
					'休闲鞋',
					'帆布鞋',
					'商务鞋'
				]
			},
			{
				title:'运动户外',
				icon:'&#xe615;',
				list:[
					'跑步鞋',
					'篮球鞋',
					'训练鞋',
					'帆布鞋',
					'运动套装',
					'卫衣/套头',
					'登山鞋',
					'徒步鞋',
					'冲锋衣/裤',
					'户外配饰',
					'望远镜',
					'烧烤用品'
				]
			},
			{
				title:'体育健康',
				icon:'&#xe61b;',
				list:[
					'自行车',
					'极限轮滑',
					'健身器械',
					'运动护具',
					'武术搏击',
					'运动器材',
					'羽毛球',
					'乒乓球',
					'麻将棋牌',
					'篮球',
					'足球',
					'瑜伽用品'
				]
			},
			{
				title:'钟表首饰',
				icon:'&#xe680;',
				list:[
					'瑞士品牌',
					'国产品牌',
					'时尚品牌',
					'日韩品牌',
					'纯金K金饰',
					'时尚饰品',
					'金银投资',
					'翡翠玉石',
					'火机烟具',
					'礼卡礼券',
					'创意礼品',
					'收藏品'
				]
			},
			{
				title:'箱包奢品',
				icon:'&#xe606;',
				list:[
					'商务手提包',
					'斜挎包',
					'手包',
					'皮带/礼盒',
					'电脑包',
					'运动包',
					'登机箱',
					'托运箱',
					'单肩包',
					'女士手提包',
					'奢品单肩包',
					'奢品手提包'
				]
			}
		]
	}
]
$('.bottom-area .main .box').append($('#bottom_list').render(bottom_list));
$('.bottom-area .main .box').children().eq(0).children('ul').children().eq(6).children().addClass('red');
$('.bottom-area .main .box').children().eq(0).children('ul').children().eq(8).children().addClass('red');

$('.bottom-area .main .box').children().eq(1).children('ul').children().eq(0).children().addClass('red');
$('.bottom-area .main .box').children().eq(1).children('ul').children().eq(3).children().addClass('red');
$('.bottom-area .main .box').children().eq(1).children('ul').children().eq(8).children().addClass('red');

$('.bottom-area .main .box').children().eq(2).children('ul').children().eq(0).children().addClass('red');
$('.bottom-area .main .box').children().eq(2).children('ul').children().eq(3).children().addClass('red');
$('.bottom-area .main .box').children().eq(2).children('ul').children().eq(11).children().addClass('red');

$('.bottom-area .main .box').children().eq(3).children('ul').children().eq(0).children().addClass('red');
$('.bottom-area .main .box').children().eq(3).children('ul').children().eq(2).children().addClass('red');
$('.bottom-area .main .box').children().eq(3).children('ul').children().eq(9).children().addClass('red');

$('.bottom-area .main .box').children().eq(4).children('ul').children().eq(0).children().addClass('red');
$('.bottom-area .main .box').children().eq(4).children('ul').children().eq(4).children().addClass('red');
$('.bottom-area .main .box').children().eq(4).children('ul').children().eq(9).children().addClass('red');

$('.bottom-area .main .box').children().eq(5).children('ul').children().eq(3).children().addClass('red');
$('.bottom-area .main .box').children().eq(5).children('ul').children().eq(8).children().addClass('red');
$('.bottom-area .main .box').children().eq(5).children('ul').children().eq(11).children().addClass('red');
var gome_help_box=[
	{
		tot:[
			{
				title:'物流配送',
				item:[
					'配送查询',
					'配送服务',
					'配送费用',
					'配送时效',
					'签收与验货'
				]
			},
			{
				title:'支付与账户',
				item:[
					'货到付款',
					'在线支付',
					'分析付款',
					'门店支付',
					'账户安全'
				]
			},
			{
				title:'售后服务',
				item:[
					'退换货服务',
					'退款说明',
					'专业维修',
					'延保服务',
					'家电回收'
				]
			},
			{
				title:'会员专区',
				item:[
					'会员专区',
					'优惠券说明',
					'美豆说明',
					'国美社区',
					'商品评价'
				]
			},
			{
				title:'购物帮助',
				item:[
					'购物保障',
					'购物流程',
					'促销优惠',
					'焦点问题',
					'联系我们'
				]
			}
		]
	}
]
$('.zwf-gome-help .gome-help-box').append($('#gome-help-box-data').render(gome_help_box));


var elevator=[
	{
		tot:[
			{
				icon:'&#xe62f;',
				title:'品质男装'
			},
			{
				icon:'&#xe62c;',
				title:'时尚女装'
			},
			{
				icon:'&#xe62d;',
				title:'时尚手表'
			},
			{
				icon:'&#xe681;',
				title:'箱包奢品'
			},
			{
				icon:'&#xe623;',
				title:'潮流鞋靴'
			},
			{
				icon:'&#xe86a;',
				title:'运动户外'
			},
			{
				icon:'&#xe62e;',
				title:'运动器械'
			},
			{
				icon:'&#xe62b;',
				title:'首饰礼品'
			}
		]
	}
]
$('.elevator').append($('#elevator-data').render(elevator));
